import type { GalleryItem } from "@/types/gallery";

/**
 * Local fallback for the gallery (used only when the CMS is unreachable or in
 * local dev with CMS_CATALOGS off). Mirrors the real job photos seeded into the
 * CMS + Bunny CDN by scripts/seed-gallery.ts — regenerate both from the same
 * MANIFEST when the photo set changes. Before/after pairs render as single
 * "Before & After" items here (the fallback GalleryItem has no before-image field).
 */
export const galleryItems: GalleryItem[] = [
  {
    id: "gal-1",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/new-garage-doors-installed-perth.webp",
    alt: "Row of new timber-look garage doors installed along a basement parking corridor with polished concrete floors",
    title: "New Timber-Look Garage Doors Installed",
    service: "New Door Installation",
    suburb: "",
    category: "Installations",
    description: "A complete multi-door installation for a Perth development — matching timber-look doors fitted along the full basement corridor, all aligned and operating smoothly.",
  },
  {
    id: "gal-2",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-torsion-spring-replacement-perth.webp",
    alt: "New black torsion spring and cable drum fitted above a grey sectional garage door after replacement",
    title: "Broken Torsion Spring Replaced",
    service: "Spring Replacement",
    suburb: "",
    category: "Before & After",
    description: "Snapped torsion spring swapped for a new high-tension spring, with the drum and shaft re-set — the door was rebalanced and back in service the same visit.",
  },
  {
    id: "gal-3",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/broken-garage-door-spring-repaired-perth.webp",
    alt: "Freshly installed torsion springs mounted above an insulated sectional garage door inside a garage",
    title: "New Torsion Springs Installed",
    service: "Spring Replacement",
    suburb: "",
    category: "Before & After",
    description: "A dangerously snapped spring replaced with a new torsion spring set — correctly tensioned, balanced and safety-checked before handover.",
  },
  {
    id: "gal-4",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/sectional-garage-door-cable-repair-perth.webp",
    alt: "Repaired grey sectional garage door panels with new hinges fitted along the panel joins",
    title: "Sectional Door Repaired After Cable Failure",
    service: "Cable Replacement",
    suburb: "",
    category: "Before & After",
    description: "This door was stuck with a snapped lift cable — new cables and hinge hardware were fitted and the panels realigned so it runs true again.",
  },
  {
    id: "gal-5",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-motor-installation-perth.webp",
    alt: "Chain-drive garage door opener being mounted to the ceiling rail during a motor installation",
    title: "Chain-Drive Garage Door Motor Installation",
    service: "Motor Installation",
    suburb: "",
    category: "Motors",
    description: "New chain-drive garage door motor installed and tuned for smooth, quiet automatic operation.",
  },
  {
    id: "gal-6",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-motor-gear-replacement-perth.webp",
    alt: "Technician holding a new nylon drive gear beside the stripped gear inside a garage door motor",
    title: "Opener Drive Gear Replacement",
    service: "Motor Repair",
    suburb: "",
    category: "Motors",
    description: "Stripped drive gear diagnosed inside the opener and replaced on the spot — a cost-effective repair that saved a full motor replacement.",
  },
  {
    id: "gal-7",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/industrial-roller-door-service-perth.webp",
    alt: "Large red industrial roller shutter door serviced and secured inside a Perth warehouse",
    title: "Industrial Roller Door Service",
    service: "Roller Door Service",
    suburb: "",
    category: "Roller Doors",
    description: "Heavy-duty warehouse roller shutter serviced and made safe for reliable daily operation.",
  },
  {
    id: "gal-8",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/commercial-roller-door-repair-perth.webp",
    alt: "Commercial roller door with a crumpled curtain sagging over the entry to business premises",
    title: "Commercial Roller Door Failure",
    service: "Roller Door Repair",
    suburb: "",
    category: "Commercial",
    description: "A collapsed roller door curtain at a commercial site — damage like this is secured fast to keep the business trading safely.",
  },
  {
    id: "gal-9",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-spring-repair-perth.webp",
    alt: "Torsion spring and chain-drive opener hardware during a spring repair on an older garage door",
    title: "Garage Door Spring Repair",
    service: "Spring Repair",
    suburb: "",
    category: "Repairs",
    description: "Ageing spring and opener hardware inspected and repaired to bring this garage door back to safe working order.",
  },
  {
    id: "gal-10",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-off-track-repair-perth.webp",
    alt: "Sectional garage door jammed off its tracks with the top panel dislodged and tilted inside the garage",
    title: "Off-Track Garage Door Repair",
    service: "Off-Track Repair",
    suburb: "",
    category: "Repairs",
    description: "This sectional door jumped its tracks and jammed mid-travel — panels were realigned and the tracking repaired so it runs safely again.",
  },
  {
    id: "gal-11",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-cable-drum-replacement-perth.webp",
    alt: "Frayed lift cable tangled around the cable drum on a rusted garage door torsion shaft",
    title: "Frayed Cable and Drum Replacement",
    service: "Cable Replacement",
    suburb: "",
    category: "Repairs",
    description: "A frayed lift cable caught on the drum — replaced before complete failure could drop the door.",
  },
  {
    id: "gal-12",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-cable-track-repair-perth.webp",
    alt: "Snapped lift cable hanging beside the curved track of an open sectional garage door",
    title: "Cable and Track Repair",
    service: "Cable Replacement",
    suburb: "",
    category: "Repairs",
    description: "Broken cable and worn track hardware replaced so this sectional door lifts evenly across both sides again.",
  },
  {
    id: "gal-13",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/car-accident-garage-door-collapse-perth.webp",
    alt: "Double garage door collapsed over two cars after a vehicle accident at a Perth home",
    title: "Car Accident Door Collapse Response",
    service: "Emergency Repair",
    suburb: "",
    category: "Repairs",
    description: "Severe vehicle-impact damage with the door collapsed over the cars inside — attended urgently to make the site safe and recover access.",
  },
  {
    id: "gal-14",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/emergency-garage-door-repair-car-impact-perth.webp",
    alt: "White sectional garage door with its bottom panel crushed inward after a car impact",
    title: "Emergency Repair After Car Impact",
    service: "Emergency Repair",
    suburb: "",
    category: "Repairs",
    description: "Car-impact damage to the lower panels — handled as an emergency call-out to secure the home and restore access.",
  },
  {
    id: "gal-15",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/emergency-garage-door-make-safe-perth.webp",
    alt: "Inside view of a sectional garage door with a badly bent bottom section letting daylight through",
    title: "Emergency Make-Safe After Car Impact",
    service: "Emergency Repair",
    suburb: "",
    category: "Repairs",
    description: "Emergency make-safe on a car-damaged door — the buckled bottom section was secured ahead of panel replacement.",
  },
  {
    id: "gal-16",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/dented-garage-door-panels-perth.webp",
    alt: "Flat-panel double garage door with dents across its lower panels after a minor car accident",
    title: "Dented Garage Door Panels",
    service: "Panel Replacement",
    suburb: "",
    category: "Repairs",
    description: "A low-speed car bump left these lower panels dented — assessed for panel replacement to bring the door back to new.",
  },
  {
    id: "gal-17",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/buckled-garage-door-panel-replacement-perth.webp",
    alt: "Beige double garage door buckled across its middle panels from impact damage",
    title: "Buckled Double Door Panel Replacement",
    service: "Panel Replacement",
    suburb: "",
    category: "Repairs",
    description: "Buckled panels across this double sectional door — repaired with replacement sections to restore strength and appearance.",
  },
  {
    id: "gal-18",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/bent-garage-door-struts-repair-perth.webp",
    alt: "Inside of a double garage door showing bent panels and reinforcement struts",
    title: "Bent Door Struts and Panels",
    service: "Door Repair",
    suburb: "",
    category: "Repairs",
    description: "Bent reinforcement struts and panels on a double sectional door — straightened and reinforced to get it operating safely again.",
  },
  {
    id: "gal-19",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-cable-replacement-willetton-perth.webp",
    alt: "Clean white sectional garage door beside a limestone wall in Willetton, Perth after new lift cables and bottom brackets were fitted",
    title: "Garage Door Cable Replacement in Willetton",
    service: "Cable Replacement",
    suburb: "Willetton",
    category: "Repairs",
    description: "New lift cables and bottom brackets fitted to this Willetton sectional door — the panels realign and the door runs smoothly and safely again.",
  },
  {
    id: "gal-20",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/steel-line-garage-door-installation-baldivis-perth.webp",
    alt: "Newly installed cream Steel-Line sectional garage door on a home in Baldivis, Perth under a clear blue sky",
    title: "New Steel-Line Garage Door Installed in Baldivis",
    service: "New Door Installation",
    suburb: "Baldivis",
    category: "Installations",
    description: "Supply and install of a new Steel-Line sectional garage door for a Baldivis home — clean lines, smooth automatic operation and a fresh street frontage.",
  },
  {
    id: "gal-21",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-hinge-roller-replacement-morley-perth.webp",
    alt: "New black hinge and roller bracket fitted to a garage door track in Morley, Perth",
    title: "Garage Door Hinge & Roller Replacement, Morley",
    service: "Hinge & Roller Replacement",
    suburb: "Morley",
    category: "Before & After",
    description: "A seized, rusted hinge and roller replaced with new hardware on this Morley garage door — before and after the repair, restoring smooth, quiet travel.",
  },
  {
    id: "gal-22",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/rusted-garage-door-spring-repair-kalamunda-perth.webp",
    alt: "Heavily rusted torsion spring on the shaft above an insulated sectional garage door in Kalamunda, Perth",
    title: "Rusted Garage Door Spring Repair in Kalamunda",
    service: "Spring Repair",
    suburb: "Kalamunda",
    category: "Repairs",
    description: "Years of moisture had corroded this Kalamunda torsion spring — inspected and replaced before it could snap and drop the door.",
  },
  {
    id: "gal-23",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/broken-garage-door-spring-replacement-duncraig-perth.webp",
    alt: "Twin torsion springs on the shaft above a garage door in Duncraig, Perth with one spring snapped",
    title: "Broken Torsion Spring Replacement in Duncraig",
    service: "Spring Replacement",
    suburb: "Duncraig",
    category: "Repairs",
    description: "One of the twin torsion springs had failed on this Duncraig door — both replaced as a set and rebalanced for even, reliable lifting.",
  },
  {
    id: "gal-24",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-cable-drum-repair-fremantle-perth.webp",
    alt: "Lift cable unwound from the cable drum on a garage door thrown out of alignment in Fremantle, Perth",
    title: "Garage Door Cable & Drum Repair in Fremantle",
    service: "Cable & Drum Repair",
    suburb: "Fremantle",
    category: "Repairs",
    description: "A lift cable had jumped the drum and pulled this Fremantle door off true — cables re-wound and the door re-tensioned and realigned.",
  },
  {
    id: "gal-25",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-lift-cable-replacement-bayswater-perth.webp",
    alt: "Frayed lift cable coiled around a red cable drum in the corner of a garage in Bayswater, Perth",
    title: "Garage Door Lift Cable Replacement in Bayswater",
    service: "Cable Replacement",
    suburb: "Bayswater",
    category: "Repairs",
    description: "Worn lift cable replaced at the drum on this Bayswater garage door before it could fail and jam the door mid-travel.",
  },
  {
    id: "gal-26",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/roller-door-repair-midland-perth.webp",
    alt: "Old cream roller shutter door with dented, bowed bottom slats on a garage in Midland, Perth",
    title: "Roller Door Repair in Midland",
    service: "Roller Door Repair",
    suburb: "Midland",
    category: "Roller Doors",
    description: "The bottom slats on this Midland roller door were dented and bowing — straightened and re-tensioned so the curtain rolls freely again.",
  },
  {
    id: "gal-27",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/roller-door-off-track-repair-gosnells-perth.webp",
    alt: "White roller door curtain pulled out of its side guide with bent slats on a garage in Gosnells, Perth",
    title: "Roller Door Off-Track Repair in Gosnells",
    service: "Roller Door Repair",
    suburb: "Gosnells",
    category: "Roller Doors",
    description: "This Gosnells roller door had jumped its side guide and creased the curtain — refitted into the track and the damaged slats corrected.",
  },
  {
    id: "gal-28",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/buckled-roller-door-repair-cannington-perth.webp",
    alt: "Charcoal roller door buckled out of its top guide beside a cracked wall on premises in Cannington, Perth",
    title: "Buckled Roller Door Repair in Cannington",
    service: "Roller Door Repair",
    suburb: "Cannington",
    category: "Roller Doors",
    description: "A charcoal roller door forced out of its guides in Cannington — the curtain was re-seated and the door made safe and operational again.",
  },
  {
    id: "gal-29",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/corroded-torsion-spring-replacement-armadale-perth.webp",
    alt: "Close-up of a badly corroded, rust-covered garage door torsion spring in Armadale, Perth",
    title: "Corroded Torsion Spring Replacement, Armadale",
    service: "Spring Replacement",
    suburb: "Armadale",
    category: "Repairs",
    description: "This Armadale torsion spring was heavily corroded and past its safe life — replaced with a new high-cycle spring and rebalanced.",
  },
  {
    id: "gal-30",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/emergency-garage-door-repair-southern-river-perth.webp",
    alt: "White sectional garage door buckled and hanging out of its tracks at a home in Southern River, Perth",
    title: "Emergency Garage Door Repair in Southern River",
    service: "Emergency Repair",
    suburb: "Southern River",
    category: "Repairs",
    description: "Called out to this Southern River home after the sectional door buckled off its tracks — secured on the spot and repaired to restore safe access.",
  },
  {
    id: "gal-31",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/emergency-sectional-door-repair-canning-vale-perth.webp",
    alt: "Sectional garage door with buckled panels hanging under a carport beside a car in Canning Vale, Perth",
    title: "Emergency Sectional Door Repair, Canning Vale",
    service: "Emergency Repair",
    suburb: "Canning Vale",
    category: "Repairs",
    description: "An after-hours callout in Canning Vale for a sectional door that folded under load — panels supported and the door made safe the same visit.",
  },
  {
    id: "gal-32",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/sectional-garage-door-repair-thornlie-perth.webp",
    alt: "Beige sectional garage door part-open with a bent panel under a carport beside a car in Thornlie, Perth",
    title: "Sectional Garage Door Repair in Thornlie",
    service: "Sectional Door Repair",
    suburb: "Thornlie",
    category: "Repairs",
    description: "A bent panel had this Thornlie sectional door jamming mid-travel — realigned and repaired so it opens and closes cleanly again.",
  },
  {
    id: "gal-33",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/commercial-roller-shutter-service-malaga-perth.webp",
    alt: "Extension ladder against a large galvanised industrial roller shutter inside a warehouse in Malaga, Perth",
    title: "Commercial Roller Shutter Service in Malaga",
    service: "Commercial Roller Door Service",
    suburb: "Malaga",
    category: "Commercial",
    description: "Servicing a full-height industrial roller shutter at a Malaga warehouse — barrel, motor and curtain checked to keep the loading bay running.",
  },
  {
    id: "gal-34",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/roller-door-repair-wanneroo-perth.webp",
    alt: "White roller door curtain dislodged from its guide against a brick wall on a garage in Wanneroo, Perth",
    title: "Roller Door Repair in Wanneroo",
    service: "Roller Door Repair",
    suburb: "Wanneroo",
    category: "Roller Doors",
    description: "This Wanneroo roller door had pulled free of its guide and creased the curtain — refitted, straightened and re-tensioned for smooth operation.",
  },
  {
    id: "gal-35",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-motor-installation-ellenbrook-perth.webp",
    alt: "Belt-drive garage door opener mounted to the ceiling rail above a sectional door in Ellenbrook, Perth",
    title: "Garage Door Motor Installation in Ellenbrook",
    service: "Motor Installation",
    suburb: "Ellenbrook",
    category: "Motors",
    description: "New belt-drive opener installed and tuned for this Ellenbrook garage — quiet, smooth automatic operation with safety sensors fitted.",
  },
  {
    id: "gal-36",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/commercial-roller-door-repair-kewdale-perth.webp",
    alt: "Light-blue commercial roller shutter bowed out of its guide above a loading bay in Kewdale, Perth",
    title: "Commercial Roller Door Repair in Kewdale",
    service: "Commercial Roller Door Repair",
    suburb: "Kewdale",
    category: "Commercial",
    description: "A commercial roller shutter forced out of its guide at a Kewdale unit — re-seated and repaired fast to keep the business secure and trading.",
  },
  {
    id: "gal-37",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/storm-damaged-garage-door-repair-mandurah-perth.webp",
    alt: "White double sectional garage door collapsed and buckled outward after storm damage at a home in Mandurah, Perth",
    title: "Storm-Damaged Garage Door Repair in Mandurah",
    service: "Storm Damage Repair",
    suburb: "Mandurah",
    category: "Repairs",
    description: "Storm winds folded this Mandurah double garage door out of its opening — attended urgently to make the site safe and plan panel replacement.",
  },
  {
    id: "gal-38",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-spring-replacement-rockingham-perth.webp",
    alt: "Newly fitted torsion spring on the shaft above a garage door against a limestone wall in Rockingham, Perth",
    title: "Garage Door Spring Replacement in Rockingham",
    service: "Spring Replacement",
    suburb: "Rockingham",
    category: "Before & After",
    description: "Before and after: a worn torsion spring replaced with a new high-cycle spring on this Rockingham door, then rebalanced and safety-checked.",
  },
];
