import type { GalleryItem } from "@/types/gallery";

/**
 * Local fallback for the gallery (used only when the CMS is unreachable or in
 * local dev with CMS_CATALOGS off). Mirrors the real job photos seeded into the
 * CMS + Bunny CDN by scripts/seed-gallery.ts — regenerate both from the same
 * MANIFEST when the photo set changes. Before/after pairs render as single
 * "Before & After" items here (the fallback GalleryItem has no before-image field).
 */
export const galleryItems: GalleryItem[] = [
  {
    id: "gal-1",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/new-garage-doors-installed-perth.webp",
    alt: "Row of new timber-look garage doors installed along a basement parking corridor with polished concrete floors",
    title: "New Timber-Look Garage Doors Installed",
    service: "New Door Installation",
    suburb: "",
    category: "Installations",
    description: "A complete multi-door installation for a Perth development — matching timber-look doors fitted along the full basement corridor, all aligned and operating smoothly.",
  },
  {
    id: "gal-2",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-torsion-spring-replacement-perth.webp",
    alt: "New black torsion spring and cable drum fitted above a grey sectional garage door after replacement",
    title: "Broken Torsion Spring Replaced",
    service: "Spring Replacement",
    suburb: "",
    category: "Before & After",
    description: "Snapped torsion spring swapped for a new high-tension spring, with the drum and shaft re-set — the door was rebalanced and back in service the same visit.",
  },
  {
    id: "gal-3",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/broken-garage-door-spring-repaired-perth.webp",
    alt: "Freshly installed torsion springs mounted above an insulated sectional garage door inside a garage",
    title: "New Torsion Springs Installed",
    service: "Spring Replacement",
    suburb: "",
    category: "Before & After",
    description: "A dangerously snapped spring replaced with a new torsion spring set — correctly tensioned, balanced and safety-checked before handover.",
  },
  {
    id: "gal-4",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/sectional-garage-door-cable-repair-perth.webp",
    alt: "Repaired grey sectional garage door panels with new hinges fitted along the panel joins",
    title: "Sectional Door Repaired After Cable Failure",
    service: "Cable Replacement",
    suburb: "",
    category: "Before & After",
    description: "This door was stuck with a snapped lift cable — new cables and hinge hardware were fitted and the panels realigned so it runs true again.",
  },
  {
    id: "gal-5",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-motor-installation-perth.webp",
    alt: "Chain-drive garage door opener being mounted to the ceiling rail during a motor installation",
    title: "Chain-Drive Garage Door Motor Installation",
    service: "Motor Installation",
    suburb: "",
    category: "Motors",
    description: "New chain-drive garage door motor installed and tuned for smooth, quiet automatic operation.",
  },
  {
    id: "gal-6",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-motor-gear-replacement-perth.webp",
    alt: "Technician holding a new nylon drive gear beside the stripped gear inside a garage door motor",
    title: "Opener Drive Gear Replacement",
    service: "Motor Repair",
    suburb: "",
    category: "Motors",
    description: "Stripped drive gear diagnosed inside the opener and replaced on the spot — a cost-effective repair that saved a full motor replacement.",
  },
  {
    id: "gal-7",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/industrial-roller-door-service-perth.webp",
    alt: "Large red industrial roller shutter door serviced and secured inside a Perth warehouse",
    title: "Industrial Roller Door Service",
    service: "Roller Door Service",
    suburb: "",
    category: "Roller Doors",
    description: "Heavy-duty warehouse roller shutter serviced and made safe for reliable daily operation.",
  },
  {
    id: "gal-8",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/commercial-roller-door-repair-perth.webp",
    alt: "Commercial roller door with a crumpled curtain sagging over the entry to business premises",
    title: "Commercial Roller Door Failure",
    service: "Roller Door Repair",
    suburb: "",
    category: "Commercial",
    description: "A collapsed roller door curtain at a commercial site — damage like this is secured fast to keep the business trading safely.",
  },
  {
    id: "gal-9",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-spring-repair-perth.webp",
    alt: "Torsion spring and chain-drive opener hardware during a spring repair on an older garage door",
    title: "Garage Door Spring Repair",
    service: "Spring Repair",
    suburb: "",
    category: "Repairs",
    description: "Ageing spring and opener hardware inspected and repaired to bring this garage door back to safe working order.",
  },
  {
    id: "gal-10",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-off-track-repair-perth.webp",
    alt: "Sectional garage door jammed off its tracks with the top panel dislodged and tilted inside the garage",
    title: "Off-Track Garage Door Repair",
    service: "Off-Track Repair",
    suburb: "",
    category: "Repairs",
    description: "This sectional door jumped its tracks and jammed mid-travel — panels were realigned and the tracking repaired so it runs safely again.",
  },
  {
    id: "gal-11",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-cable-drum-replacement-perth.webp",
    alt: "Frayed lift cable tangled around the cable drum on a rusted garage door torsion shaft",
    title: "Frayed Cable and Drum Replacement",
    service: "Cable Replacement",
    suburb: "",
    category: "Repairs",
    description: "A frayed lift cable caught on the drum — replaced before complete failure could drop the door.",
  },
  {
    id: "gal-12",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/garage-door-cable-track-repair-perth.webp",
    alt: "Snapped lift cable hanging beside the curved track of an open sectional garage door",
    title: "Cable and Track Repair",
    service: "Cable Replacement",
    suburb: "",
    category: "Repairs",
    description: "Broken cable and worn track hardware replaced so this sectional door lifts evenly across both sides again.",
  },
  {
    id: "gal-13",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/car-accident-garage-door-collapse-perth.webp",
    alt: "Double garage door collapsed over two cars after a vehicle accident at a Perth home",
    title: "Car Accident Door Collapse Response",
    service: "Emergency Repair",
    suburb: "",
    category: "Repairs",
    description: "Severe vehicle-impact damage with the door collapsed over the cars inside — attended urgently to make the site safe and recover access.",
  },
  {
    id: "gal-14",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/emergency-garage-door-repair-car-impact-perth.webp",
    alt: "White sectional garage door with its bottom panel crushed inward after a car impact",
    title: "Emergency Repair After Car Impact",
    service: "Emergency Repair",
    suburb: "",
    category: "Repairs",
    description: "Car-impact damage to the lower panels — handled as an emergency call-out to secure the home and restore access.",
  },
  {
    id: "gal-15",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/emergency-garage-door-make-safe-perth.webp",
    alt: "Inside view of a sectional garage door with a badly bent bottom section letting daylight through",
    title: "Emergency Make-Safe After Car Impact",
    service: "Emergency Repair",
    suburb: "",
    category: "Repairs",
    description: "Emergency make-safe on a car-damaged door — the buckled bottom section was secured ahead of panel replacement.",
  },
  {
    id: "gal-16",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/dented-garage-door-panels-perth.webp",
    alt: "Flat-panel double garage door with dents across its lower panels after a minor car accident",
    title: "Dented Garage Door Panels",
    service: "Panel Replacement",
    suburb: "",
    category: "Repairs",
    description: "A low-speed car bump left these lower panels dented — assessed for panel replacement to bring the door back to new.",
  },
  {
    id: "gal-17",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/buckled-garage-door-panel-replacement-perth.webp",
    alt: "Beige double garage door buckled across its middle panels from impact damage",
    title: "Buckled Double Door Panel Replacement",
    service: "Panel Replacement",
    suburb: "",
    category: "Repairs",
    description: "Buckled panels across this double sectional door — repaired with replacement sections to restore strength and appearance.",
  },
  {
    id: "gal-18",
    image: "https://jadara-hub.b-cdn.net/capital-garage-door/gallery/bent-garage-door-struts-repair-perth.webp",
    alt: "Inside of a double garage door showing bent panels and reinforcement struts",
    title: "Bent Door Struts and Panels",
    service: "Door Repair",
    suburb: "",
    category: "Repairs",
    description: "Bent reinforcement struts and panels on a double sectional door — straightened and reinforced to get it operating safely again.",
  },
];
