import type { GalleryItem } from "@/types/gallery";

/**
 * Gallery (Page Type: visual proof). Placeholder job photos until connected
 * to real CRM job photos — swap this module for a live feed in
 * lib/data/gallery.ts without touching components or the page template.
 */
export const galleryItems: GalleryItem[] = [
  {
    id: "gal-1",
    image: "/images/services/spring-repair.webp",
    alt: "Broken garage door spring repaired on a Perth home",
    title: "Broken Spring Replacement",
    service: "Spring Repair",
    suburb: "Joondalup",
    category: "Repairs",
    description: "Snapped torsion spring replaced same-day, door rebalanced and tested for safe operation.",
  },
  {
    id: "gal-2",
    image: "/images/services/garage-door-installation.webp",
    alt: "New sectional garage door installed on a Perth home",
    title: "Sectional Door Installation",
    service: "Installation",
    suburb: "Canning Vale",
    category: "Installations",
    description: "Full sectional door install with new smart motor, weather seals, and remote setup.",
  },
  {
    id: "gal-3",
    image: "/images/services/garage-door-opener-repair.webp",
    alt: "Garage door motor and opener repaired in Perth",
    title: "Motor & Opener Repair",
    service: "Motor Repair",
    suburb: "Scarborough",
    category: "Motors",
    description: "Diagnosed a failing circuit board and replaced the opener — door back in service within the hour.",
  },
  {
    id: "gal-4",
    image: "/images/services/garage-door-repair.webp",
    alt: "Roller door tracks repaired on a Perth home",
    title: "Roller Door Track Repair",
    service: "Roller Door Repair",
    suburb: "Fremantle",
    category: "Roller Doors",
    description: "Realigned bent tracks and replaced worn rollers on a residential roller door.",
  },
  {
    id: "gal-5",
    image: "/images/services/emergency-garage-door-service.webp",
    alt: "Commercial roller shutter servicing in Perth",
    title: "Commercial Roller Shutter Service",
    service: "Commercial Servicing",
    suburb: "Osborne Park",
    category: "Commercial",
    description: "Scheduled maintenance on a commercial roller shutter, including lubrication and safety checks.",
  },
  {
    id: "gal-6",
    image: "/images/services/garage-door-maintenance.webp",
    alt: "Garage door before and after maintenance service in Perth",
    title: "Before & After Full Service",
    service: "Servicing",
    suburb: "Rockingham",
    category: "Before & After",
    description: "Annual service on a noisy, sticking door — new rollers and hardware restored smooth, quiet operation.",
  },
  {
    id: "gal-7",
    image: "/images/services/garage-door-installation.webp",
    alt: "New garage door motor installed in Perth",
    title: "Smart Motor Upgrade",
    service: "Motor Installation",
    suburb: "Baldivis",
    category: "Motors",
    description: "Upgraded an ageing manual door to a smart motor with app and remote control.",
  },
  {
    id: "gal-8",
    image: "/images/services/garage-door-repair.webp",
    alt: "Garage door panel replacement in Perth",
    title: "Damaged Panel Replacement",
    service: "Panel Repair",
    suburb: "Midland",
    category: "Repairs",
    description: "Replaced a dented sectional panel after vehicle impact, matched to the existing door finish.",
  },
  {
    id: "gal-9",
    image: "/images/services/garage-door-installation.webp",
    alt: "Commercial garage door installation in Perth",
    title: "Commercial Door Installation",
    service: "Commercial Installation",
    suburb: "Welshpool",
    category: "Commercial",
    description: "Installed a heavy-duty commercial sectional door for a Perth warehouse unit.",
  },
];
