import type { Review, ReviewsSummary } from "@/types/review";

/**
 * Reviews page (Page Type: trust). Placeholder testimonial data — swap this
 * module for a live Google Reviews / CRM feed in lib/data/reviews.ts without
 * touching components or the page template.
 */
export const reviewsSummary: ReviewsSummary = {
  averageRating: 4.9,
  totalReviews: 248,
  googleProfileUrl: "https://g.page/r/CapitalGarageDoorPerth/reviews",
  googleWriteReviewUrl: "https://g.page/r/CapitalGarageDoorPerth/review",
};

export const reviews: Review[] = [
  {
    id: "rev-1",
    customerName: "Sarah M.",
    rating: 5,
    text: "Our spring snapped on a Sunday morning and Capital had a technician out within two hours. Fixed, tested, and gone before lunch. Couldn't ask for better emergency service.",
    suburb: "Joondalup",
    service: "Emergency Repairs",
    source: "Google",
    date: "2026-05-12",
    featured: true,
  },
  {
    id: "rev-2",
    customerName: "David T.",
    rating: 5,
    text: "Replaced our old manual door with a new sectional door and smart motor. The team was tidy, on time, and walked us through the app setup before they left.",
    suburb: "Canning Vale",
    service: "Installations",
    source: "Google",
    date: "2026-04-28",
    featured: true,
  },
  {
    id: "rev-3",
    customerName: "Priya R.",
    rating: 5,
    text: "Motor died after 12 years and they had a like-for-like replacement quoted and fitted the next day. Quiet, smooth, and a fair price compared to two other quotes we got.",
    suburb: "Fremantle",
    service: "Motor Replacement",
    source: "Facebook",
    date: "2026-04-15",
    featured: true,
  },
  {
    id: "rev-4",
    customerName: "Mark H.",
    rating: 4,
    text: "Good honest repair — diagnosed a worn roller and a misaligned track, fixed both for less than I expected. Door runs much quieter now.",
    suburb: "Scarborough",
    service: "Repairs",
    source: "Google",
    date: "2026-03-30",
  },
  {
    id: "rev-5",
    customerName: "Emily W.",
    rating: 5,
    text: "Booked the annual service plan after a recommendation from a neighbour. Technician was thorough, lubricated everything, and flagged a cable that was starting to fray before it became a problem.",
    suburb: "Midland",
    service: "Servicing",
    source: "Google",
    date: "2026-03-18",
    featured: true,
  },
  {
    id: "rev-6",
    customerName: "Liam P.",
    rating: 5,
    text: "Door wouldn't open and we had a tradesman's van trapped in the garage. Called Capital, they talked us through a temporary manual release over the phone, then came out same day to fix it properly.",
    suburb: "Rockingham",
    service: "Emergency Repairs",
    source: "Google",
    date: "2026-03-02",
    featured: true,
  },
  {
    id: "rev-7",
    customerName: "Hannah C.",
    rating: 5,
    text: "From quote to install was under a week. The new double door looks fantastic and the price was clear from the start — no surprise extras on the day.",
    suburb: "Joondalup",
    service: "Installations",
    source: "Website",
    date: "2026-02-22",
  },
  {
    id: "rev-8",
    customerName: "Anthony G.",
    rating: 4,
    text: "Quick, professional repair on a bent track panel after a minor car bump. Explained the cause clearly and gave tips to avoid it happening again.",
    suburb: "Canning Vale",
    service: "Repairs",
    source: "Google",
    date: "2026-02-09",
  },
  {
    id: "rev-9",
    customerName: "Olivia S.",
    rating: 5,
    text: "Upgraded our motor to a quieter belt-drive unit with a backup battery. Brilliant during the last power outage — door still worked perfectly.",
    suburb: "Fremantle",
    service: "Motor Replacement",
    source: "Google",
    date: "2026-01-27",
  },
  {
    id: "rev-10",
    customerName: "Ryan B.",
    rating: 5,
    text: "Friendly, on time, and genuinely cared about getting it right. The servicing visit caught a worn spring before it failed — saved us an emergency call-out down the track.",
    suburb: "Scarborough",
    service: "Servicing",
    source: "Facebook",
    date: "2026-01-14",
  },
  {
    id: "rev-11",
    customerName: "Grace L.",
    rating: 5,
    text: "Excellent communication throughout — text updates on arrival time, clear quote before any work started, and the door has never run smoother.",
    suburb: "Midland",
    service: "Repairs",
    source: "Google",
    date: "2025-12-20",
  },
  {
    id: "rev-12",
    customerName: "Jack F.",
    rating: 5,
    text: "Called about a door stuck halfway open late on a Friday night. Technician arrived within the hour and had it sorted in twenty minutes. Highly recommend for emergencies.",
    suburb: "Rockingham",
    service: "Emergency Repairs",
    source: "Google",
    date: "2025-12-08",
  },
  {
    id: "rev-13",
    customerName: "Chloe N.",
    rating: 5,
    text: "Full install for our new build — coordinated perfectly with our builder's timeline and the finish quality is spot on. Would use again without hesitation.",
    suburb: "Joondalup",
    service: "Installations",
    source: "Google",
    date: "2025-11-25",
  },
  {
    id: "rev-14",
    customerName: "Ben K.",
    rating: 4,
    text: "Solid repair job on a noisy roller door. Fair price, arrived in the booked window, cleaned up after themselves.",
    suburb: "Canning Vale",
    service: "Repairs",
    source: "Website",
    date: "2025-11-10",
  },
  {
    id: "rev-15",
    customerName: "Amelia D.",
    rating: 5,
    text: "Old motor was on its last legs and starting to smell hot. Replaced it the same week with a proper safety-certified unit. Feels much safer with the kids around now.",
    suburb: "Fremantle",
    service: "Motor Replacement",
    source: "Google",
    date: "2025-10-29",
  },
  {
    id: "rev-16",
    customerName: "Noah J.",
    rating: 5,
    text: "Signed up for the maintenance plan after our last unexpected repair bill. Two visits in and everything's running like new — worth every cent.",
    suburb: "Scarborough",
    service: "Servicing",
    source: "Google",
    date: "2025-10-11",
  },
];
