import type { Review, ReviewsSummary } from "@/types/review";

/**
 * Reviews page (Page Type: trust). Real customer reviews sourced from the
 * business's Google profile. Names are shortened to first name + last initial
 * for privacy; `suburb` is intentionally blank because the source reviews do
 * not include a location (the /reviews "Reviews by Suburb" filter is hidden
 * while there is no suburb data — see app/reviews/page.tsx).
 *
 * `service` is mapped onto the canonical REVIEW_SERVICE_OPTIONS so the
 * "Reviews by Service" filter buckets each review correctly.
 *
 * When CMS_REVIEWS === "on" the live /reviews page reads from the CMS instead
 * (GET /api/reviews); this module is the fallback AND the source of truth for
 * the reviews importer (POST /admin/api/import-reviews), so keep it in sync
 * with what is seeded into the CMS.
 */
export const reviewsSummary: ReviewsSummary = {
  averageRating: 5.0,
  totalReviews: 24,
  googleProfileUrl: "https://g.page/r/CapitalGarageDoorPerth/reviews",
  googleWriteReviewUrl: "https://g.page/r/CapitalGarageDoorPerth/review",
};

export const reviews: Review[] = [
  {
    id: "rev-janelle-s",
    customerName: "Janelle S.",
    rating: 5,
    text: "Musab was extremely efficient, professional, organised and a nice bloke. Would highly recommend his service and installation of roller doors to anyone.",
    suburb: "",
    service: "Installations",
    source: "Google",
    date: "2026-04-18",
    featured: true,
  },
  {
    id: "rev-trina-s",
    customerName: "Trina S.",
    rating: 5,
    text: "So impressed with the support from the team after two garage doors went, with a home open looming. They inspected, ordered parts and completed repairs within 24 hours. Highly recommended.",
    suburb: "",
    service: "Emergency Repairs",
    source: "Google",
    date: "2025-06-10",
    featured: true,
  },
  {
    id: "rev-andrea-r",
    customerName: "Andrea R.",
    rating: 5,
    text: "I cannot speak highly enough about this company. My garage door stopped working and my car was trapped inside. Adam was there in an hour and fixed it in 30 minutes. Friendly, professional service. I wouldn't use anyone else.",
    suburb: "",
    service: "Emergency Repairs",
    source: "Google",
    date: "2024-06-15",
    featured: true,
  },
  {
    id: "rev-stephen-o",
    customerName: "Stephen O.",
    rating: 5,
    text: "Outstanding work — replaced a broken spring and fixed a panel that was dented by a car. Prompt and efficient. Will definitely use again.",
    suburb: "",
    service: "Repairs",
    source: "Google",
    date: "2025-05-20",
  },
  {
    id: "rev-charlotte-d",
    customerName: "Charlotte D.",
    rating: 5,
    text: "I highly recommend Capital Garage Doors and am very appreciative of Moussab's excellent, prompt and efficient service. He fixed my roller door at short notice with no fuss at all. Thank you so much, Moussab.",
    suburb: "",
    service: "Repairs",
    source: "Google",
    date: "2025-06-02",
  },
  {
    id: "rev-khaled-k",
    customerName: "Khaled K.",
    rating: 5,
    text: "Capital Garage Doors provided exceptional service from start to finish. Their team was professional, prompt and knowledgeable, ensuring my garage door was repaired efficiently. The quality of work exceeded my expectations and the pricing was fair.",
    suburb: "",
    service: "Repairs",
    source: "Google",
    date: "2025-07-09",
    featured: true,
  },
  {
    id: "rev-marty-p",
    customerName: "Marty P.",
    rating: 5,
    text: "Sam and crew responded very quickly on the same day to fix my broken garage door panel. The door works even better now. Highly recommend them — will be booking them for the regular service from now on.",
    suburb: "",
    service: "Repairs",
    source: "Google",
    date: "2024-06-22",
    featured: true,
  },
  {
    id: "rev-jacques-d",
    customerName: "Jacques D.",
    rating: 5,
    text: "Had an issue with the motor on an old SDO-1 unit. Called on a Monday, asked for Wednesday morning, and he came in early and gave me options. I chose to fully replace my system and rollers, and he removed the old system and rails too. Quick and easy — not even 45 minutes, with no issues.",
    suburb: "",
    service: "Motor Replacement",
    source: "Google",
    date: "2024-07-11",
    featured: true,
  },
  {
    id: "rev-kasem-s",
    customerName: "Kasem S.",
    rating: 5,
    text: "Thank you Capital, and special thanks to Mr. Musab and Mr. K for this perfect and more than wonderful work. The motor and spring were replaced with great precision and speed. Very nice and respectful people.",
    suburb: "",
    service: "Motor Replacement",
    source: "Google",
    date: "2026-01-14",
  },
  {
    id: "rev-joe-f",
    customerName: "Joe F.",
    rating: 5,
    text: "I had a fantastic experience with Capital Garage Doors. They went above and beyond by carrying out an emergency repair after hours. Their prompt response and expert service saved the day. I can't thank them enough for their professionalism and dedication.",
    suburb: "",
    service: "Emergency Repairs",
    source: "Google",
    date: "2024-05-30",
  },
  {
    id: "rev-gloria-l",
    customerName: "Gloria L.",
    rating: 5,
    text: "I called in the morning for a repair urgently needed and they responded with a quote right after I provided photos. Moussab arrived to do the service and carried out the work swiftly and very efficiently.",
    suburb: "",
    service: "Repairs",
    source: "Google",
    date: "2024-06-18",
  },
  {
    id: "rev-karma-t",
    customerName: "Karma T.",
    rating: 5,
    text: "Capital Garage Door was very quick to come over and immediately knew the problem. Within 30 minutes the job was done, plus he gave professional advice for future reference. Job well done!",
    suburb: "",
    service: "Repairs",
    source: "Google",
    date: "2025-06-05",
  },
  {
    id: "rev-luke-h",
    customerName: "Luke H.",
    rating: 5,
    text: "Had an issue with my garage door diagnosed within a few minutes over the phone and fixed the same day. The price was cheap and the work was completed quickly and to a good standard — made sure everything was working correctly before he left.",
    suburb: "",
    service: "Repairs",
    source: "Google",
    date: "2024-06-28",
  },
  {
    id: "rev-annabelle-p",
    customerName: "Annabelle P.",
    rating: 5,
    text: "A wire snapped on our old garage door this morning and Capital Garage Doors were able to schedule us in the same day. Fossika was on time, professional and knowledgeable. Would recommend this company for any repairs.",
    suburb: "",
    service: "Emergency Repairs",
    source: "Google",
    date: "2025-06-12",
  },
  {
    id: "rev-chantelle-n",
    customerName: "Chantelle N.",
    rating: 5,
    text: "Quick, efficient and friendly service. Really happy with Mussab's professional work — knew exactly what he needed to fix and gave us a full rundown before he left. Will definitely call again when we need service and repair work done.",
    suburb: "",
    service: "Repairs",
    source: "Google",
    date: "2025-06-20",
  },
  {
    id: "rev-ross-l",
    customerName: "Ross L.",
    rating: 5,
    text: "Great service. The team attended super quickly and solved the problem in minutes. They also previously replaced a broken motor in very quick time and at a very reasonable price. Can't recommend highly enough.",
    suburb: "",
    service: "Motor Replacement",
    source: "Google",
    date: "2024-06-09",
  },
  {
    id: "rev-ross-p",
    customerName: "Ross P.",
    rating: 5,
    text: "Great response by these guys to come to mine and rectify my remotes on the spot. Lifesavers!",
    suburb: "",
    service: "Repairs",
    source: "Google",
    date: "2025-06-25",
  },
  {
    id: "rev-sandra-f",
    customerName: "Sandra F.",
    rating: 5,
    text: "Excellent response time. They came and fixed the door very fast and with incredible professionalism. 100% recommended.",
    suburb: "",
    service: "Emergency Repairs",
    source: "Google",
    date: "2025-12-15",
  },
  {
    id: "rev-agness-t",
    customerName: "Agness T.",
    rating: 5,
    text: "Super fast and helpful — fixed my garage issue in under a minute. Highly recommend. Thank you!",
    suburb: "",
    service: "Repairs",
    source: "Google",
    date: "2025-10-22",
  },
  {
    id: "rev-carlos-f",
    customerName: "Carlos F.",
    rating: 5,
    text: "Had an event on and really needed to get my car out. They came out as soon as they could, which got me to the event on time. Would highly recommend — great response time.",
    suburb: "",
    service: "Emergency Repairs",
    source: "Google",
    date: "2024-06-14",
  },
  {
    id: "rev-harry-p",
    customerName: "Harry P.",
    rating: 5,
    text: "Contacted Sam as my garage door was broken. He was prompt in responding to my messages and came on time, was honest in his advice, and did the job promptly in 20 minutes.",
    suburb: "",
    service: "Repairs",
    source: "Google",
    date: "2024-06-19",
  },
  {
    id: "rev-duane-s",
    customerName: "Duane S.",
    rating: 5,
    text: "Good efficient work. One of the springs on my garage door snapped in half. Service was fast and efficient — both springs were replaced within an hour. Highly recommend for garage door troubles.",
    suburb: "",
    service: "Repairs",
    source: "Google",
    date: "2025-05-08",
  },
  {
    id: "rev-silva-f",
    customerName: "Silva F.",
    rating: 5,
    text: "A good company that works 24 hours. They have experience and good prices, communicate well and with respect, and make sure after the work is done that everything is working well.",
    suburb: "",
    service: "Emergency Repairs",
    source: "Google",
    date: "2025-06-30",
  },
  {
    id: "rev-jue-w",
    customerName: "Jue W.",
    rating: 5,
    text: "Musaab is an expert in this field. I just sent him a photo of my broken garage door and he straight away knew the problem. Only one side was broken, but he changed both sides for us. Much appreciated.",
    suburb: "",
    service: "Repairs",
    source: "Google",
    date: "2024-06-21",
  },
];
