import type { BrandEntity } from "@/types/brand";

/**
 * Every garage-door / motor brand seen in Perth — one entity per manufacturer. Drives the nav
 * mega-menus (logos), the two hubs (tiles, facts table, finder) and each brand page's plate.
 *
 * Facts (origin, ownership, founded, productLines) come ONLY from the official site listed in
 * `sources`; `accent` is a design choice. `dealer: true` is allowed ONLY for the eight brands
 * the site already names as authorised dealers (B&D, Steel-Line, Gliderol, Avanti, Superlift,
 * Boss Openers, Perth Windsor Doors, Jaytech) — scripts/check-brand-content.ts enforces it.
 * Filled by the 2026-08 research pass (docs/marketing/brand-research-2026-08/entities/).
 */
export const BRAND_ENTITIES: BrandEntity[] = [
  {
    slug: "merlin",
    name: "Merlin",
    kinds: ["motor"],
    accent: "#1c4fa1",
    url: "https://www.gomerlin.com.au/",
    origin: "Australia / New Zealand",
    dealer: false,
    tags: ["smart-app", "roller", "sectional", "tilt"],
    summary: "Popular myQ-connected opener brand across Australia and NZ — sectional, roller and tilt models via local dealers.",
    productLines: "Commander (Essential to Ultimate, sectional), Roller and Tilt ranges, myQ app",
    sources: [
      "https://www.gomerlin.com.au/",
      "https://www.gomerlin.com.au/products/",
      "https://www.gomerlin.com.au/garage-automation/sectional-door/",
    ],
  },
  {
    slug: "chamberlain",
    name: "Chamberlain",
    kinds: ["motor"],
    accent: "#0092bc",
    url: "https://www.chamberlaindiy.com.au/",
    origin: "USA",
    ownership: "Chamberlain Group",
    dealer: false,
    tags: ["smart-app", "roller", "sectional"],
    summary: "Chamberlain Group's Australian DIY brand — myQ-enabled RollerLift and SectionalLift openers for self-install.",
    productLines: "RollerLift, RollerLift Plus, SectionalLift, SectionalLift Plus, myQ app",
    sources: [
      "https://www.chamberlaindiy.com.au/about-us/",
      "https://www.chamberlaindiy.com.au/garage-door-openers/",
    ],
  },
  {
    slug: "liftmaster",
    name: "LiftMaster",
    aliases: ["Lift Master"],
    kinds: ["motor"],
    accent: "#f47216",
    origin: "USA",
    dealer: false,
    tags: ["sectional"],
    summary: "Chamberlain Group's professional-grade opener line — chain and belt-drive sectional models distributed in Australia.",
    productLines: "LiftMaster Professional range — LM60K, LM60R, LM1000K, LM1000R",
    sources: [
      "https://www.liftmaster.com.au/about.html",
      "https://www.liftmaster.com.au/garage_doors.html",
      "https://www.liftmaster.com.au/",
    ],
  },
  {
    slug: "b-and-d",
    name: "B&D",
    aliases: ["B & D", "B and D", "BnD"],
    kinds: ["door", "motor"],
    logo: "/images/brands/bd.webp",
    accent: "#1a1a1a",
    url: "https://www.bnd.com.au/",
    origin: "Australia",
    dealer: true,
    tags: ["smart-app", "roller", "sectional", "commercial", "australian-made"],
    summary: "Australia's best-known door and opener manufacturer — Roll-A-Door, Panelift and Smart Pro, with a 10-year warranty.",
    productLines: "Roll-A-Door, Panelift, Series 2 Commercial Roller Door, Controll-A-Door, Smart Pro, B&D App",
    sources: ["https://www.bnd.com.au/", "https://www.bnd.com.au/garage-doors/"],
  },
  {
    slug: "gliderol",
    name: "Gliderol",
    kinds: ["door", "motor"],
    logo: "/images/brands/gliderol.webp",
    accent: "#003a70",
    url: "https://gliderol.com.au/",
    origin: "Australia",
    founded: 1974,
    dealer: true,
    tags: ["roller", "sectional", "australian-made"],
    summary: "Australian-owned manufacturer since 1974 — roller and sectional doors with the Genesis and Glidermatic opener ranges.",
    productLines: "Essentials Series (roller), Genesis Series, Glidermatic GRD",
    sources: [
      "https://gliderol.com.au/",
      "https://gliderol.com.au/garage-doors/roller/",
      "https://gliderol.com.au/wp-content/uploads/2024/11/Gliderol-Warranty-Conditions-of-Sale-Statement.pdf",
    ],
  },
  {
    slug: "steel-line",
    name: "Steel-Line",
    aliases: ["Steel Line", "Steelline"],
    kinds: ["door", "motor"],
    logo: "/images/brands/steel-line.webp",
    accent: "#4a4a4a",
    url: "https://www.steel-line.com.au/",
    origin: "Australia",
    dealer: true,
    tags: ["roller", "sectional", "tilt", "commercial", "australian-made"],
    summary: "Australia's largest garage door manufacturer — roller, sectional, tilt and commercial doors with F-linX automation.",
    productLines: "Custom Collection, Sectional Doors, Roller Doors, Tilt Doors, Specialty Doors, F-linX",
    sources: ["https://www.steel-line.com.au/", "https://www.steel-line.com.au/garage-doors-perth/"],
  },
  {
    slug: "centurion",
    name: "Centurion Garage Doors",
    kinds: ["door", "motor"],
    accent: "#b91c1c",
    url: "https://www.cgdoors.com.au/",
    origin: "Australia",
    founded: 1976,
    dealer: false,
    tags: ["smart-app", "roller", "sectional", "commercial"],
    summary: "Family-owned Australian manufacturer since 1976 — sectional, roller and commercial doors, plus the Euro 1250 opener.",
    productLines: "TimbaLook Premium Series, Cosmopolitan Colorbond Sectional, Sunshine Series, Architectural Series, Urban Series, Euro 1250 opener, MY CGD app",
    sources: ["https://www.cgdoors.com.au/"],
  },
  // No live official site (2026-08): facts limited to the dealer relationship + reseller listings.
  {
    slug: "boss",
    name: "Boss Openers",
    matchTerms: ["Boss opener", "Boss motor", "Boss garage"],
    kinds: ["motor"],
    logo: "/images/brands/boss-openers.webp",
    accent: "#1e3a5f",
    origin: "Australia",
    dealer: true,
    tags: [],
    summary: "Opener and remote brand sold through Australian dealers — we supply, install and service it.",
    productLines: "Garage door openers, gate openers and remotes",
    sources: [
      "http://www.bossoperators.com.au/",
      "https://www.steel-line.com.au/",
      "https://www.top4.com.au/business/boss-garage-door-openers-72165",
      "https://www.magickey.com.au/garage-door-opener/Boss-Steel-Line",
    ],
  },
  {
    slug: "ata",
    name: "ATA",
    kinds: ["motor"],
    accent: "#f2b705",
    url: "https://www.automatictechnology.com/au",
    origin: "Australia",
    ownership: "B&D Group",
    founded: 1978,
    dealer: false,
    tags: ["roller", "commercial", "australian-made"],
    summary: "Australian-engineered opener brand since 1978, part of the B&D Group — the Dave commercial operator and EasyRoller.",
    productLines: "Dave (commercial operator), EasyRoller (residential roller opener)",
    sources: ["https://www.automatictechnology.com/au"],
  },
  {
    slug: "grifco",
    name: "Grifco",
    kinds: ["motor"],
    accent: "#009999",
    url: "https://www.grifco.com.au/",
    origin: "Australia",
    dealer: false,
    tags: ["smart-app", "commercial", "australian-made"],
    summary: "Australian-made commercial door automation — nine Drive-series motors and a Fire Shutter Operator, myQ-connected.",
    productLines: "E-Drive, M-Drive, EHD Drive, D-Drive, H-Drive, LR-Drive, S-Drive, LS-Drive, LG-Drive, Fire Shutter Operator",
    sources: ["https://www.grifco.com.au/"],
  },
  {
    slug: "avanti",
    name: "Avanti",
    kinds: ["motor"],
    logo: "/images/brands/avanti.webp",
    accent: "#0057a8",
    url: "https://avantigdo.com/",
    origin: "Philippines",
    dealer: true,
    tags: ["sectional", "roller"],
    summary: "Philippines-manufactured opener brand distributed in Australia — SDO4 sectional and RDO roller door openers.",
    productLines: "SDO4 (sectional), RDO1, RDO10C (roller), D5-EVO, Vantage (gate motors)",
    sources: ["https://avantigdo.com/", "https://avantigdo.com/about-us/"],
  },
  {
    slug: "superlift",
    name: "Superlift",
    kinds: ["motor"],
    logo: "/images/brands/superlift.webp",
    accent: "#1a5fb4",
    url: "https://www.superliftgdo.com.au/",
    origin: "Perth, WA",
    dealer: true,
    tags: ["roller", "sectional", "tilt"],
    summary: "WA-headquartered garage door opener brand with over 30 years in the market — roller, sectional and tilt models.",
    productLines: "RDO-5, RDO-6 (roller), SDO-5 (sectional/tilt), SSLG-2 (swing gate)",
    sources: ["https://www.superliftgdo.com.au/"],
  },
  {
    slug: "jaytech",
    name: "Jaytech",
    kinds: ["motor"],
    logo: "/images/brands/jaytech.webp",
    accent: "#1a1a1a",
    url: "https://www.jaytechopeners.com.au/",
    origin: "Australia",
    founded: 2012,
    dealer: true,
    tags: ["sectional", "roller", "commercial"],
    summary: "Australian-owned opener brand founded 2012 by two garage door technicians — the 1200 V4+ and RDO roller ranges.",
    productLines: "Jaytech 1200 V4+ (sectional), RDO 1000+, RDO 1800+ (roller)",
    sources: ["https://www.jaytechopeners.com.au/"],
  },
  {
    slug: "guardian",
    name: "Guardian",
    matchTerms: ["Guardian opener", "Guardian motor", "Guardian door"],
    kinds: ["motor", "door"],
    accent: "#1b3a57",
    origin: "USA / Perth, WA",
    dealer: false,
    tags: ["sectional", "roller"],
    summary: "Two unrelated 'Guardian' businesses: a US opener/hardware brand and an independent Perth door supplier.",
    productLines: "Models 415/425, Pro Series (US openers); sectional, roller and custom doors (Perth's Guardian Doors)",
    sources: ["https://adhguardianusa.com/", "https://guardiandoors.com.au/about/"],
  },
  {
    slug: "dominator",
    name: "Dominator",
    kinds: ["door", "motor"],
    accent: "#002d5c",
    url: "https://www.dominatornsw.com.au/",
    origin: "New Zealand",
    dealer: false,
    tags: ["smart-app", "roller", "sectional", "tilt", "commercial"],
    summary: "New Zealand-manufactured door brand sold through Australian state networks — Milano, Nevada, Sierra and Kinetic ranges.",
    productLines: "Milano, Nevada, Sierra, Kinetic, Flex-A-Door",
    sources: ["https://www.dominatornsw.com.au/", "https://www.dominator.co.nz/about-us"],
  },
  {
    slug: "marantec",
    name: "Marantec",
    kinds: ["motor"],
    accent: "#1f4f8f",
    url: "https://www.marantec.com/en/",
    origin: "Germany",
    founded: 1989,
    dealer: false,
    tags: ["smart-app", "sectional", "tilt"],
    summary: "German-engineered opener brand founded 1989 — Comfort 200/300 Series with the maveo smart app, ISO 9001 certified.",
    productLines: "Comfort 300 Series, Comfort 200 Series, Comfort 260 accu, Comfort Speed Series, maveo app",
    sources: ["https://www.marantec.com/en/door-operators-in-the-private-sector/garage-door-openers"],
  },
  {
    slug: "genie",
    name: "Genie",
    matchTerms: ["Genie opener", "Genie motor"],
    kinds: ["motor"],
    accent: "#005baa",
    url: "https://www.geniecompany.com/",
    origin: "USA",
    ownership: "GMI Holdings Inc.",
    dealer: false,
    tags: ["smart-app"],
    summary: "US opener brand (GMI Holdings) with the Aladdin Connect app — no confirmed official Australian distributor.",
    productLines: "Residential and Commercial opener ranges, Aladdin Connect app",
    sources: ["https://www.geniecompany.com/"],
  },
  {
    slug: "somfy",
    name: "Somfy",
    kinds: ["motor"],
    accent: "#0057b8",
    url: "https://www.somfy.com.au/",
    origin: "France",
    ownership: "Somfy Group",
    dealer: false,
    tags: ["smart-app"],
    summary: "Global Somfy Group's Australian arm — electric garage door automation with the TaHoma smart home hub.",
    productLines: "Electric Garage doors, TaHoma smart home hub",
    sources: ["https://www.somfy.com.au/"],
  },
  {
    slug: "magic-button",
    name: "Magic Button",
    matchTerms: ["Magic Button"],
    kinds: ["motor"],
    accent: "#003876",
    url: "https://www.liftmaster.com.au/",
    origin: "Australia",
    ownership: "Liftmaster Electronics Pty Ltd",
    dealer: false,
    tags: ["australian-made"],
    summary: "The strongest 'local-made' claim among Perth opener brands — controls and PCBs designed and manufactured in Australia.",
    productLines: "Magic Button Radio Control Hand Transmitter, Magic Button electronic controls & PCBs, Performance Range",
    sources: ["https://www.liftmaster.com.au/about.html", "https://www.liftmaster.com.au/"],
  },
  {
    slug: "nice",
    name: "Nice",
    matchTerms: ["Nice motor", "Nice opener", "Nice automation"],
    kinds: ["motor"],
    accent: "#e2001a",
    url: "https://www.niceaustralia.com.au/",
    origin: "Italy",
    dealer: false,
    tags: ["smart-app"],
    summary: "Italian automation brand with an Australian arm (Nice Australia, SA) — Nice Opera and the MyNice Welcome smart app.",
    productLines: "Nice Opera, MyNice Welcome app, GDS gate/industrial range (Australian-made)",
    sources: [
      "https://www.niceforyou.com/au/solutions/automation-for-garage-doors",
      "https://www.niceaustralia.com.au/",
    ],
  },
  {
    slug: "dea",
    name: "DEA",
    matchTerms: ["DEA motor", "DEA opener", "DEA System"],
    kinds: ["motor"],
    accent: "#ffcc00",
    url: "https://www.deasystem.com/en/",
    origin: "Italy",
    dealer: false,
    tags: ["sectional", "roller"],
    summary: "Italian-manufactured gate and door automation brand — sectional and roller shutter motors with NET-COM diagnostics.",
    productLines: "Overhead doors, sectional doors, sliding/swing gates, roller shutters, NET-COM platform",
    sources: ["https://www.deasystem.com/en/"],
  },
  {
    slug: "danmar",
    name: "Danmar",
    kinds: ["door"],
    accent: "#333333",
    url: "https://www.danmardoorswa.com.au/",
    origin: "Perth, WA",
    dealer: false,
    tags: ["sectional", "commercial", "australian-made", "wa-made"],
    summary: "Perth-owned manufacturer for 35+ years — timber, aluminium and Thermopanel sectional doors, incl. side-slide designs.",
    productLines: "Natural Timber Doors, Contemporary Aluminium Doors, Thermopanels, Side Slide Sectional Doors",
    sources: ["https://www.danmardoorswa.com.au/about/", "https://www.danmardoorswa.com.au/our-range/"],
  },
  {
    slug: "taurean",
    name: "Taurean",
    kinds: ["door"],
    accent: "#1e5aa8",
    url: "https://www.taureands.com.au/",
    origin: "Australia",
    ownership: "Stramit Corporation / Fletcher Building Group",
    dealer: false,
    tags: ["roller", "sectional", "commercial", "australian-made"],
    summary: "Australian-made roller and sectional doors from Stramit/Fletcher Building — the Windstrong cyclone-rated range.",
    productLines: "Windstrong (roller doors), TauraEdge (track system)",
    sources: ["https://www.taureands.com.au/"],
  },
  {
    slug: "perth-windsor-doors",
    name: "Perth Windsor Doors",
    kinds: ["door"],
    logo: "/images/brands/perth-windsor-doors.webp",
    accent: "#0f4c81",
    url: "https://perthwindsordoors.com/",
    origin: "Perth, WA",
    dealer: true,
    tags: ["roller", "sectional", "commercial", "australian-made", "wa-made"],
    summary: "Locally manufactured in WA for 25+ years — roller, sectional and cyclonic doors, plus a preferred Steel-Line dealership.",
    productLines: "Roller Doors, Sectional Doors, DecoWood Doors, Insulated Doors, Cyclonic Doors",
    sources: ["https://perthwindsordoors.com/"],
  },
  {
    slug: "doorworks",
    name: "Doorworks",
    kinds: ["door"],
    accent: "#f5c400",
    url: "https://doorworks.com.au/",
    origin: "Australia",
    ownership: "BX Bunka Australia Group",
    founded: 2012,
    dealer: false,
    tags: ["roller", "sectional", "commercial", "australian-made"],
    summary: "Sydney-manufactured door brand since 2012, part of BX Bunka Australia — sectional, roller and bespoke ranges.",
    productLines: "Sectional doors, premium bespoke doors, roller doors, specialty garage doors",
    sources: ["https://doorworks.com.au/about-us/"],
  },
  {
    slug: "best-doors",
    name: "Best Doors",
    kinds: ["door"],
    accent: "#334155",
    origin: "Australia",
    founded: 1975,
    dealer: false,
    tags: ["roller", "sectional", "commercial"],
    summary: "Family-owned QLD/SA retailer since 1975, stocking Danmar timber doors and its own Selections designer range.",
    productLines: "Selections (designer doors), stocked Danmar timber doors, commercial/industrial range",
    sources: [
      "https://bestdoors.com.au/about-us/",
      "https://www.bestdoors.com.au/residential/garage-doors/timber-garage-doors/",
    ],
  },
  {
    slug: "hormann",
    name: "Hörmann",
    aliases: ["Hormann"],
    kinds: ["door"],
    accent: "#003764",
    url: "https://www.4ddoors.com.au/",
    origin: "Germany",
    dealer: false,
    tags: ["sectional", "roller", "commercial"],
    summary: "Germany's largest door manufacturer, distributed in Australia exclusively through 4Ddoors — sectional to industrial.",
    productLines: "Garage doors (up-and-over, sectional, side-sliding), rolling shutters, industrial/high-speed doors",
    sources: [
      "https://www.4ddoors.com.au/page/4ddoors-powered-by-hormann",
      "https://en.wikipedia.org/wiki/H%C3%B6rmann",
    ],
  },
  {
    slug: "gryphon",
    name: "Gryphon",
    kinds: ["door", "motor"],
    accent: "#1a1a1a",
    url: "https://gryphongaragedoors.com/",
    origin: "Perth, WA",
    dealer: false,
    tags: ["roller", "sectional", "commercial", "australian-made", "wa-made"],
    summary: "WA-made doors for 25+ years — sectional, roller and wood-look finishes, with a 12-year structural warranty.",
    productLines: "Sectional doors, Roller doors, DecoWood, Timba Grain, hand-painted Teak and Jarrah",
    sources: ["https://gryphongaragedoors.com/"],
  },
];
